#pragma kernel CSMain
RWTexture2D<float4> Result;
float radius;
float4 brushColor;
float2 position;

[numthreads(32,32,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float dist = distance(id.xy, float2(position.x, position.y));
    int mask = step(dist, radius);
    Result[id.xy] = lerp(Result[id.xy], brushColor, mask);
}

//delete everything under \ComponentModelCache then you can use IntelliSense